openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8082
  description: Generated server url
paths:
  /api/v1/receipts/{transactionReferenceNumber}:
    get:
      tags:
      - receipt-controller
      operationId: receipt
      parameters:
      - name: transactionReferenceNumber
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReceiptResponse'
components:
  schemas:
    ItemResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        count:
          type: integer
          format: int32
        amount:
          type: number
          format: double
    ReceiptResponse:
      type: object
      properties:
        timestamp:
          type: string
        studentId:
          type: integer
          format: int64
        studentName:
          type: string
        schoolName:
          type: string
        grade:
          type: string
        transactionReferenceNumber:
          type: string
        cardNumber:
          type: string
        cardHolderName:
          type: string
        cardType:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemResponse'
        total:
          type: number
          format: double
